---
abstract: unknown
author:
  - 'Tom Schindl <tom.schindl@bestsolution.at>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-TomKit
no_index:
  directory:
    - t
    - inc
requires:
  APR::Request: 0
  Apache::Test: 0
  XML::LibXML: 1.59
  XML::LibXSLT: 1.59
  mod_perl2: 0
version: 0.01_7
